figsave_dir_sensitivity <- paste0("figures/slopes_2/s",parset,"_")

ggsave(fig_yale_florida_regression,file=paste0(figsave_dir_sensitivity,"yale_florida_regression.pdf"), width=8, height=5)
ggsave(fig_yale_florida_residuals,file=paste0(figsave_dir_sensitivity,"yale_florida_residuals.pdf"), width=8, height=5)
ggsave(fig_yale_florida_qq,file=paste0(figsave_dir_sensitivity,"yale_florida_qq.pdf"), width=8, height=5)

save_figlist(figlist_ct_dat_refined,figsave_dir_sensitivity,"ct_dat_refined","pdf")
ggsave(fig_ct_fit,file=paste0(figsave_dir_sensitivity,"ct_fit.pdf"), width=8, height=8)
ggsave(fig_ct_fit_symp,file=paste0(figsave_dir_sensitivity,"ct_fit_symp.pdf"), width=8, height=8)
save_figlist(fig_ct_fit_list,figsave_dir_sensitivity,"ct_fit","pdf")
ggsave(fig_peak_ct,file=paste0(figsave_dir_sensitivity,"peak_ct.pdf"), width=8, height=8)
ggsave(fig_t_peak,file=paste0(figsave_dir_sensitivity,"t_peak.pdf"), width=8, height=8)
ggsave(fig_t_onset_to_peak,file=paste0(figsave_dir_sensitivity,"t_onset_to_peak.pdf"), width=8, height=8)
ggsave(fig_t_peak_to_recovery,file=paste0(figsave_dir_sensitivity,"t_peak_to_recovery.pdf"), width=8, height=8)
ggsave(fig_duration_of_infection,file=paste0(figsave_dir_sensitivity,"duration_of_infection.pdf"), width=8, height=8)
ggsave(fig_sigma,file=paste0(figsave_dir_sensitivity,"sigma.pdf"), width=8, height=8)
ggsave(fig_dpmean_withprior,file=paste0(figsave_dir_sensitivity,"dpmean_withprior.pdf"), width=8, height=5)
ggsave(fig_wpmean_withprior,file=paste0(figsave_dir_sensitivity,"wpmean_withprior.pdf"), width=8, height=5)
ggsave(fig_wrmean_withprior,file=paste0(figsave_dir_sensitivity,"wrmean_withprior.pdf"), width=8, height=5)
ggsave(fig_dpmean,file=paste0(figsave_dir_sensitivity,"dpmean.pdf"), width=8, height=5)
ggsave(fig_wpmean,file=paste0(figsave_dir_sensitivity,"wpmean.pdf"), width=8, height=5)
ggsave(fig_wrmean,file=paste0(figsave_dir_sensitivity,"wrmean.pdf"), width=8, height=5)
ggsave(fig_infdurmean,file=paste0(figsave_dir_sensitivity,"infdurmean.pdf"), width=8, height=5)
ggsave(fig_gemlmean,file=paste0(figsave_dir_sensitivity,"gemlmean.pdf"), width=8, height=5)
ggsave(fig_peak_ct_overall,file=paste0(figsave_dir_sensitivity,"peak_ct_overall.pdf"), width=8, height=5)
ggsave(fig_t_onset_to_peak_overall,file=paste0(figsave_dir_sensitivity,"t_onset_to_peak_overall.pdf"), width=8, height=5)
ggsave(fig_t_peak_to_recovery_overall,file=paste0(figsave_dir_sensitivity,"t_peak_to_recovery_overall.pdf"), width=8, height=5)
ggsave(fig_infection_duration_overall,file=paste0(figsave_dir_sensitivity,"infection_duration_overall.pdf"), width=8, height=5)
ggsave(fig_peak_symptomatic,file=paste0(figsave_dir_sensitivity,"peak_symptomatic.pdf"), width=8, height=5)
ggsave(fig_wp_symptomatic,file=paste0(figsave_dir_sensitivity,"wp_symptomatic.pdf"), width=8, height=5)
ggsave(fig_wr_symptomatic,file=paste0(figsave_dir_sensitivity,"wr_symptomatic.pdf"), width=8, height=5)
ggsave(fig_infection_duration_symptomatic,file=paste0(figsave_dir_sensitivity,"infection_duration_symptomatic.pdf"), width=8, height=5)
ggsave(fig_infection_ppv_ma,file=paste0(figsave_dir_sensitivity,"infection_ppv_ma.pdf"), width=8, height=5)
ggsave(fig_infection_ppv_ma_raw,file=paste0(figsave_dir_sensitivity,"infection_ppv_ma_raw.pdf"), width=8, height=5)
ggsave(fig_infection_ppv_ma_paired,file=paste0(figsave_dir_sensitivity,"infection_ppv_ma_paired.pdf"), width=8, height=5)
ggsave(fig_onset_given_infection_ppv_ma,file=paste0(figsave_dir_sensitivity,"onset_given_infection_ppv_ma.pdf"), width=8, height=5)
ggsave(fig_onset_given_infection_ppv_ma_raw,file=paste0(figsave_dir_sensitivity,"onset_given_infection_ppv_ma_raw.pdf"), width=8, height=5)
ggsave(fig_onset_given_infection_ppv_ma_paired,file=paste0(figsave_dir_sensitivity,"onset_given_infection_ppv_ma_paired.pdf"), width=8, height=5)
ggsave(fig_ct_trajectory_inference,file=paste0(figsave_dir_sensitivity,"ct_trajectory_inference.pdf"), width=8, height=5)

