figsave_dir_sensitivity <- paste0("figures/slopes_2/s",parset,"_")

ggsave(fig_yale_florida_regression,file=paste0(figsave_dir_sensitivity,"yale_florida_regression.png"), width=8, height=5)
ggsave(fig_yale_florida_residuals,file=paste0(figsave_dir_sensitivity,"yale_florida_residuals.png"), width=8, height=5)
ggsave(fig_yale_florida_qq,file=paste0(figsave_dir_sensitivity,"yale_florida_qq.png"), width=8, height=5)

save_figlist(figlist_ct_dat_refined,figsave_dir_sensitivity,"ct_dat_refined","png")
ggsave(fig_ct_fit,file=paste0(figsave_dir_sensitivity,"ct_fit.png"), width=8, height=8)
ggsave(fig_ct_fit_symp,file=paste0(figsave_dir_sensitivity,"ct_fit_symp.png"), width=8, height=8)
save_figlist(fig_ct_fit_list,figsave_dir_sensitivity,"ct_fit","png")
ggsave(fig_peak_ct,file=paste0(figsave_dir_sensitivity,"peak_ct.png"), width=8, height=8)
ggsave(fig_t_peak,file=paste0(figsave_dir_sensitivity,"t_peak.png"), width=8, height=8)
ggsave(fig_t_onset_to_peak,file=paste0(figsave_dir_sensitivity,"t_onset_to_peak.png"), width=8, height=8)
ggsave(fig_t_peak_to_recovery,file=paste0(figsave_dir_sensitivity,"t_peak_to_recovery.png"), width=8, height=8)
ggsave(fig_duration_of_infection,file=paste0(figsave_dir_sensitivity,"duration_of_infection.png"), width=8, height=8)
ggsave(fig_sigma,file=paste0(figsave_dir_sensitivity,"sigma.png"), width=8, height=8)
ggsave(fig_dpmean_withprior,file=paste0(figsave_dir_sensitivity,"dpmean_withprior.png"), width=8, height=5)
ggsave(fig_wpmean_withprior,file=paste0(figsave_dir_sensitivity,"wpmean_withprior.png"), width=8, height=5)
ggsave(fig_wrmean_withprior,file=paste0(figsave_dir_sensitivity,"wrmean_withprior.png"), width=8, height=5)
ggsave(fig_dpmean,file=paste0(figsave_dir_sensitivity,"dpmean.png"), width=8, height=5)
ggsave(fig_wpmean,file=paste0(figsave_dir_sensitivity,"wpmean.png"), width=8, height=5)
ggsave(fig_wrmean,file=paste0(figsave_dir_sensitivity,"wrmean.png"), width=8, height=5)
ggsave(fig_infdurmean,file=paste0(figsave_dir_sensitivity,"infdurmean.png"), width=8, height=5)
ggsave(fig_gemlmean,file=paste0(figsave_dir_sensitivity,"gemlmean.png"), width=8, height=5)
ggsave(fig_peak_ct_overall,file=paste0(figsave_dir_sensitivity,"peak_ct_overall.png"), width=8, height=5)
ggsave(fig_t_onset_to_peak_overall,file=paste0(figsave_dir_sensitivity,"t_onset_to_peak_overall.png"), width=8, height=5)
ggsave(fig_t_peak_to_recovery_overall,file=paste0(figsave_dir_sensitivity,"t_peak_to_recovery_overall.png"), width=8, height=5)
ggsave(fig_infection_duration_overall,file=paste0(figsave_dir_sensitivity,"infection_duration_overall.png"), width=8, height=5)
ggsave(fig_peak_symptomatic,file=paste0(figsave_dir_sensitivity,"peak_symptomatic.png"), width=8, height=5)
ggsave(fig_wp_symptomatic,file=paste0(figsave_dir_sensitivity,"wp_symptomatic.png"), width=8, height=5)
ggsave(fig_wr_symptomatic,file=paste0(figsave_dir_sensitivity,"wr_symptomatic.png"), width=8, height=5)
ggsave(fig_infection_duration_symptomatic,file=paste0(figsave_dir_sensitivity,"infection_duration_symptomatic.png"), width=8, height=5)
ggsave(fig_infection_ppv_ma,file=paste0(figsave_dir_sensitivity,"infection_ppv_ma.png"), width=8, height=5)
ggsave(fig_infection_ppv_ma_raw,file=paste0(figsave_dir_sensitivity,"infection_ppv_ma_raw.png"), width=8, height=5)
ggsave(fig_infection_ppv_ma_paired,file=paste0(figsave_dir_sensitivity,"infection_ppv_ma_paired.png"), width=8, height=5)
ggsave(fig_onset_given_infection_ppv_ma,file=paste0(figsave_dir_sensitivity,"onset_given_infection_ppv_ma.png"), width=8, height=5)
ggsave(fig_onset_given_infection_ppv_ma_raw,file=paste0(figsave_dir_sensitivity,"onset_given_infection_ppv_ma_raw.png"), width=8, height=5)
ggsave(fig_onset_given_infection_ppv_ma_paired,file=paste0(figsave_dir_sensitivity,"onset_given_infection_ppv_ma_paired.png"), width=8, height=5)
ggsave(fig_ct_trajectory_inference,file=paste0(figsave_dir_sensitivity,"ct_trajectory_inference.png"), width=8, height=5)

